language: python
dist: bionic
python:
  - "3.6"
  - "3.8"

# command to install testing dependencies
install:
  - pip install nose

script:
  - python setup.py nosetests
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
